### PR TITLE
Chimatara patch 1

### PR DESCRIPTION
**Pull request by Chimatara**
Changes from Git pages to GitHub Pages in line 222

### CODE REVIEW

**Comment by Chimatara** [comment]
Hi @AndreaSanchezTapia I made the changes.
Can you review it? and is my branching still pointing to my main forked repo? I tried pointing it to the OLS main repo

**Comment by AndreaSanchezTapia** [comment]
It's pointing correctly, thank you! can you revert the changes in OLS4 so we can merge?

**Review by bebatut — DISMISSED** [review]
Thanks

**Comment by Chimatara** [comment]
I just reverted the changes, thank you @AndreaSanchezTapia

**Review by bebatut — APPROVED** [review]

**Pull request merged**
