### PR TITLE
Speedblog post-Richard Dushime

### PR DESCRIPTION
**Pull request by richarddushime**
Here is the Speedblog Post created in markdown file under Posts and  created a folder with name  ols7 under images folder  where i uploaded the images  used  in the blog post

### CODE REVIEW

**Comment by richarddushime** [comment]
Hi @NPDebs @bebatut 
Here Requesting for your review 
Thanks

**Comment by bebatut** [comment]
Thanks @richarddushime for the blogpost. I made some formatting changes:  https://deploy-preview-623--ols-bebatut.netlify.app/posts/2023/06/14/ols-7-richard-ols-mentorship-jouney/
I hope they fit to you

One comment: it would be nice to have an image to put on the top. Do you have sth?

**Comment by richarddushime** [comment]
> Thanks @richarddushime for the blogpost. I made some formatting changes: https://deploy-preview-623--ols-bebatut.netlify.app/posts/2023/06/14/ols-7-richard-ols-mentorship-jouney/ I hope they fit to you
> Thank you for the Adjustement it really made it look so nice and organized 

> One comment: it would be nice to have an image to put on the top. Do you have sth?
yes i wanted to put one but i was not able  if you can choose one from the pictures i uploaded in images/ols7/ directory you can get one  which fits

**Comment by bebatut** [comment]
Do you have any preference for the image to pick?

**Comment by richarddushime** [comment]
Yeah the logo for the project or   the group picture 🖼️

**Review by bebatut — COMMENTED** [review]
I forgot. Could you add alt text (between `[` in `]`)  to all your images, please? 
It ensures people who use screen readers and other assistive technologies, such as those who are blind, have low-vision, or have cognitive disabilities, can understand the intent of the image. 
Thanks a lot

**Comment by richarddushime** [comment]
> I forgot. Could you add alt text (between `[` in `]`) to all your images, please? It ensures people who use screen readers and other assistive technologies, such as those who are blind, have low-vision, or have cognitive disabilities, can understand the intent of the image. Thanks a lot

Thank you  i will do so

**Comment by richarddushime** [comment]
> > I forgot. Could you add alt text (between `[` in `]`) to all your images, please? It ensures people who use screen readers and other assistive technologies, such as those who are blind, have low-vision, or have cognitive disabilities, can understand the intent of the image. Thanks a lot
> 
> Thank you i will do so

Done

**Comment by richarddushime** [comment]
Hi @bebatut 
is there anything  i could add ? 
just inquiring

**Review by bebatut — APPROVED** [review]
Ready for merge now

**Comment by richarddushime** [comment]
> Ready for merge now. Thanks @richarddushime

Thanks and welcome

**Pull request merged**
