### PR TITLE
added three pillar icons

### PR DESCRIPTION
**Pull request by jilaga**

### CODE REVIEW

**Comment by jilaga** [comment]
> Thank you!!

a pleasure boss!

**Comment by bebatut** [comment]
Just a quick comment. @jilaga would it be possible to make also a PR with the icons to the branding repo? Thanks a lot

**Comment by jilaga** [comment]
> Just a quick comment. @jilaga would it be possible to make also a PR with the icons to the branding repo? Thanks a lot

alright boss @bebatut, 👌😎

**Comment by NPDebs** [comment]
Thanks for the PR, Jilaga! These icons are gorgeous. 😻❤️

I was going to ask for them in the _svg_ format as well, but I see you already added them in the branding repo. Thanks a lot!

**Pull request merged**
