### PR TITLE
Create Outreachy Project Timeline Blog

### PR DESCRIPTION
**Pull request by NPDebs**
This PR piggybacks on PR #501.
Based on the ideas shared by Outreachy participants, on what a project timeline should look like, [Bisola15](https://github.com/Bisola15) created this blogpost, to be referenced by present and future participants.

Screenshot (356)

**Note For Reviewers**
We thought of adding a nice image to the post. Do let us know if you have one in mind, or if we can make that call. Thanks!

### CODE REVIEW

**Comment by NPDebs** [comment]
The test is failing because the author "bisola" is not a recognised member.

**Comment by Bisola15** [comment]
> The test is failing because the author "bisola" is not a recognised member.

Ouuuu... Can it be fixed by removing my name?

**Comment by NPDebs** [comment]
> > The test is failing because the author "bisola" is not a recognised member.
> 
> Ouuuu... Can it be fixed by removing my name?

Yeah. Most likely...

Here's the image you suggested. 😀
Screenshot (358)

**Comment by Bisola15** [comment]
Looking great 💃🏾💃🏾💃🏾💃🏾💃🏾
Well done boo

**Comment by bebatut** [comment]
I close this PR as outreachy is now done. Thanks!

**Pull request closed without merging**
