### PR TITLE
add draft participation guidelines

### PR DESCRIPTION
**Pull request by yochannah**
addresses #32 

draft, open to discussion, modification, etc. Remix of a few of my favourite bits of various guidelines.

### CODE REVIEW

**Comment by bebatut** [comment]
I will have a look later.
Quick question: should we update the [CODE of Conduct file](https://github.com/open-life-science/open-life-science.github.io/blob/master/CODE_OF_CONDUCT.md) to fit to the same content? Maybe we could share the content between both files to avoid redundancy of text and forgot to update both in case we change sth

**Comment by yochannah** [comment]
Yes, I think they should be the same thing, and ideally only in one place!

**Comment by yochannah** [comment]
following team meeting - 

- [ ] add link to CoC on website
- [ ] use jekyll embeds and add to syllabus.

**Comment by bebatut** [comment]
This PR should
- fix #32
- fix #36

**Comment by yochannah** [comment]
okay - there is now only one CoC. It *doesn't* use jekyll includes because includes can't be markdown, unfourtunately, only HTML. in lieu of this, it's linked to from the syllabus. 

This change also adds a link to the syllabus in the about section.

There's a tiny CSS change to make sure no-image hero sections have readible text (was dark grey on dark grey, is now whiteish on dark grey).

**Comment by bebatut** [comment]
Looks good.

I managed to get the Jekyll include working: needed to change the include directory in the `.config.yml` file and update all previous includes.
So we should be able now to use includes from everywhere and from Markdown.

To keep the `CODE_OF_CONDUCT.md` clean from metadata, I created a `code-of-conduct.md` page with just metadata and includes. I also added an image:

Screenshot 2019-10-15 at 15 53 34

Let me know what do you think about that

**Pull request merged**
