### PR TITLE
Use updated 'border-less' logos in website for scalability.

### PR DESCRIPTION
**Pull request by NPDebs**
In PR #748, we had added logos to website's headers. During the review, there was a concern raised about the size of the logos (being too small).
After the changes went live, our genius designer advised that the logos would inevitably appear better if the frames bordering them were to be removed.

In PR #[88](https://github.com/open-life-science/branding/pull/88), updated versions of the theme were uploaded to replace the old ones. This was done to promote the scalability of the images.

Here, these changes have been made:
- Added the two new logos to the `logos` sub-directory under `/images`.
- Edited the new path to these images in the `default-header` & `openseeds-header`.

**Screenshots:**
ols_logo_PR
openseeds_logo_PR

**Live link [here](https://deploy-preview-749--ols-bebatut.netlify.app/openseeds/)**...
Thanks for following the train of thought without getting lost. :)

### CODE REVIEW

**Comment by NPDebs** [comment]
@jilaga & @yochannah This looks much better, me thinks! 😍
What say you - ready to go live with it?

**Comment by jilaga** [comment]
Me thinks so too! carry on Genius @NPDebs

**Comment by yochannah** [comment]
@NPDebs this looks good for Open Seeds, but I think a tiny bit of padding around the OLS logo might help (sorry - too much before, now too little)

**Comment by NPDebs** [comment]
Good eyes!

**Comment by NPDebs** [comment]
Okay, I think we're looking much better now. Yo, does [this](https://deploy-preview-749--ols-bebatut.netlify.app/openseeds/) get your _approval_ approval?

**Comment by NPDebs** [comment]
@yochannah Non-urgent, but simply calling your attention to this. Please, review when you can. Thanks!

**Review by yochannah — APPROVED** [review]
Yes!

approval^2

**Pull request merged**
