### PR TITLE
Update custom.scss

### PR DESCRIPTION
**Pull request by oluwatobiBolu**
to remove the distracting green links on the website
part of what i reverted in the first pull request
this tackles issue #417 only
please review 
thanks for the earlier guide

### CODE REVIEW

**Comment by oluwatobiBolu** [comment]
> As defined in the [OLS Outreachy contribution guide](https://docs.google.com/document/d/1HP7qTBe-6YrCUYAVkrT441rGtF6zxzNbbz2E5RWQvTM/edit?usp=sharing),
> 
> * If someone else has already commented, let them try first
> * If they don’t update after three days, the issue is “free” again, and you can pick it up.
> 
> @hsadia538 were the first one to comment the issue #417. Maybe we could let them to the first try on that

Ok. I had just read the guide now. I wasn't aware we had to comment before working on it. A review would still be appreciated.

**Comment by bebatut** [comment]
Maybe @hsadia538 could review it
@baimamboukar created also a similar Pull Request #426 you could review too

**Comment by oluwatobiBolu** [comment]
> Maybe @hsadia538 could review it @baimamboukar created also a similar Pull Request #426 you could review too

@bebatut  could it be given a review now, i think it's past the three waiting days
thanks for your taking out of your time

**Comment by bebatut** [comment]
Yes it should be reviewed now :smile: 

One first quick comment: with your changes, it is now difficult to see where there are links

**Comment by oluwatobiBolu** [comment]
> Yes it should be reviewed now 😄
> 
> One first quick comment: with your changes, it is now difficult to see where there are links

changes have been made
Screenshot (154)

**Comment by bebatut** [comment]
Thanks. Can you check using [Wave](https://wave.webaim.org/) if this changes the accessibility (contrasts, etc)?

**Comment by oluwatobiBolu** [comment]
> Thanks. Can you check using [Wave](https://wave.webaim.org/) if this changes the accessibility (contrasts, etc)?

i have changed the link color from #48b87d to a more darker #265F3F to pass the contrast accessibility

Screenshot (156)
Screenshot (157)

**Comment by 1Joda** [comment]
Hey @oluwatobiBolu,
I think the green color throughout the page should remain the same (The logo, icons plus these links) so instead of using green at all, the color can just be black but a bit transparent and on hover, turn fully opaque.
Or something like that

**Comment by oluwatobiBolu** [comment]
> Hey @oluwatobiBolu, I think the green color throughout the page should remain the same (The logo, icons plus these links) so instead of using green at all, the color can just be black but a bit transparent and on hover, turn fully opaque. Or something like that

The point of making it green is to entirely differentiate the links 
and i think it drives that point when it is a brighter color

**Comment by vasconsaurus** [comment]
this PR also fixes issue #438

**Comment by yochannah** [comment]
Quick note from my side - I think the colour looks fine, but it also makes it harder to tell there is a link there since it's similar to the main text colour. Any suggestions for ways to make the link affordance more obvious? https://web.accessibility.duke.edu/link-and-button-affordance/

**Comment by vasconsaurus** [comment]
> Quick note from my side - I think the colour looks fine, but it also makes it harder to tell there is a link there since it's similar to the main text colour. Any suggestions for ways to make the link affordance more obvious? https://web.accessibility.duke.edu/link-and-button-affordance/

I think we could maybe see if a slightly lighter color would work (I do think in the avatars that green looks a bit too dark). We could also maybe keep the underline, but move it closer to the text, and make both the same color. Like in the page you linked:

Screen Shot 2022-10-24 at 08 30 57

**Comment by oluwatobiBolu** [comment]
@yochannah @vasconsaurus i changed the text decoration property of the main contents
it looks something like this. Is this what you have in mind? 
Screenshot (171)

**Comment by vasconsaurus** [comment]
> @yochannah @vasconsaurus i changed the text decoration property of the main contents it looks something like this. Is this what you have in mind? 

I think the links are pretty clear now. Even though we brought back the underline for this test, I don't think it's as 'vibrant'(?), as it was before. From my 'other-applicant-observer' position, this seems like it could be a solution.

We should probably check what @bebatut thinks as well

**Comment by bebatut** [comment]
We come back there to the issue that underlining links make the text hard to read for people with dyslexia

**Comment by yochannah** [comment]
Closing this - thanks for the contributions 🙏  in this case we are updating the whole theme so this PR isn't needed anymore.

**Pull request closed without merging**
