### PR TITLE
Added a google translate button to the footer section

### PR DESCRIPTION
**Pull request by Abiola-Zeenat**
Addressing #199 
.I added a google translate button which allows the web pages to be translated into different languages.
Screenshot ols1

### CODE REVIEW

**Comment by NPDebs** [comment]
Hi @Abiola-Zeenat 🙂

It's good practice to provide details about the issue solved in your PR.

A screenshot would also help the reviewer(s).

**Comment by Abiola-Zeenat** [comment]
> Hi @Abiola-Zeenat 🙂
> 
> It's good practice to provide details about the issue solved in your PR.
> 
> A screenshot would also help the reviewer(s).

Noted!!Thanks @NPDebs .

**Comment by Abiola-Zeenat** [comment]
Should I add the Screenshot as a comment or should I make a new pull Request?

**Comment by NPDebs** [comment]
> Should I add the Screenshot as a comment or should I make a new pull Request?

You're most welcome!

Just edit the current PR. Add the screnshot and description. 🚀💪🏼

**Review by NPDebs — APPROVED** [review]
Yaay! It works.

Tested it locally and got this result, @bebatut...
Screenshot (279)

Screenshot (280)

If only there was a way to set this up, without the language options covering content.

**Comment by Abiola-Zeenat** [comment]
yes, i thought of that too but then it is only up while selecting your language,it goes back down as soon as you have selected your language

**Comment by NPDebs** [comment]
> yes, i thought of that too but then it is only up while selecting your language,it goes back down as soon as you have selected your language

True, true. 💯

LGTM.

**Comment by Abiola-Zeenat** [comment]
Thanks

**Comment by bebatut** [comment]
I did not hide for me the language option. When closing it, it goes back to the english version.
Another approach could be the one taken here: https://training.galaxyproject.org/
See implementation here: https://github.com/galaxyproject/training-material/blob/main/_includes/resource-handson.html#L29

**Comment by Abiola-Zeenat** [comment]
> Thanks @Abiola-Zeenat for the work here
> 
> I did not hide for me the language option. When closing it, it goes back to the english version. Another approach could be the one taken here: https://training.galaxyproject.org/ See implementation here: https://github.com/galaxyproject/training-material/blob/main/_includes/resource-handson.html#L29

yes @bebatut, it goes back to the english version after closing. so are you suggesting that I use the recommended approach instead.

**Comment by NPDebs** [comment]
> > Thanks @Abiola-Zeenat for the work here
> > 
> > I did not hide for me the language option. When closing it, it goes back to the english version. Another approach could be the one taken here: https://training.galaxyproject.org/ See implementation here: https://github.com/galaxyproject/training-material/blob/main/_includes/resource-handson.html#L29
> 
> yes @bebatut, it goes back to the english version after closing. so are you suggesting that I use the recommended approach instead.

Hi @Abiola-Zeenat. I believe what @bebatut said is that the code didn't have the desired behaviour when she tested it on her end.

She suggests you try the approach recommended by "galaxyproject." 👍🏻

**Comment by yochannah** [comment]
I'm closing this as out of date - thanks for the contribution!

**Pull request merged**
