### PR TITLE
Update Nebula microgrant policy

### PR DESCRIPTION
**Pull request by iramosp**
This PR updates the Nebula microgrant policy. 

Tagging @pherterich and @bethaniley, for content review. Does this draft reflect our decisions? 
Please make any necessary changes. 

Tagging @NPDebs for technical review after approval by finance team. 

:+1::tada: First of all, thanks for taking the time to contribute! :tada::+1:

## FOR CONTRIBUTOR

* [ ] I have read the [CONTRIBUTING.md](https://github.com/open-life-science/open-life-science.github.io/blob/main/CONTRIBUTING.md) document

PR Type: 
* [ ] This PR adds a new blog post
* [x] This PR does something else (explain above)

 
## FOR REVIEWERS

Thanks for taking the time to review! :heart:

Here are the list of things to make sure of:
* [x] The website builds (a check will fail if not)
* [ ] All images have been added within the Pull Request and they have Alt text
* [ ] If there are paragraphs or text, the key messages are highlighted
* [ ] All internal links (within OLS website) use the [`{% link path_to_file.md %}` format](https://jekyllrb.com/docs/liquid/tags/#link)
* [ ] The preview corresponds to the changes described in the Pull Request
* [ ] The code is tidy and passes the linting tests

### CODE REVIEW

**Comment by pherterich** [comment]
It reflects what we said we would cover. I will let @bethaniley comment in more detail on the process as I'm pretty sure we don't actually have a reimbursement form at the moment.

**Comment by bethaniley** [comment]
There's a draft reimbursement form (on the internal repo - I'll tag you both in the issue) but it hasn't been tested yet. I can prioritise finishing it so we can use it for Nebula! I'm also happy to make changes to it if they're needed 🙂

**Comment by iramosp** [comment]
@bethaniley, I left some comments in the reimbursement form issue. Looking at the form made me think about this other question I added to the microgrant policy FAQ:

> Will OLS cover transaction and conversion fees?
We try to reimburse you in the currency of your preference to avoid conversion fees. Please note, we might not be able to make transfers of certain currencies to accounts in certain countries; we will let you know if that's the case

Questions for you both @bethaniley and @pherterich:
- Is that an accurate answer about transaction fees?
- Is the microgrant policy ready to be published or do you prefer that we have more clarity about the reimbursement process?

**Comment by yochannah** [comment]
Hey folks - we need to wrap this up so Irene can set expectations with participants. It sounds like we're all agreed on the basics, but we need to finalise the microgrant form. I'll merge this and we can tweak later if anything needs changes

**Review by yochannah — APPROVED** [review]

**Comment by pherterich** [comment]
Sorry, haven't followed up on this - must have missed the update notification. We cover transaction fees where we know they exist and usually pick an option that reduces them as much as possible.

General Q: when things have a deadline that hasn't been added to the PR or issue, can we get an additional ping on slack with a deadline? Happy to prioritise things, but need to know what requires a more urgent answer.

**Pull request merged**
