### PR TITLE
Proofread and correct typos

### PR DESCRIPTION
**Pull request by NPDebs**
This PR fixes issue #428.
The README was meticulously examined for errors and the grammar was also minimally restructured. 
ols-pr

Kindly review. Thank you!

### CODE REVIEW

**Comment by NPDebs** [comment]
@bebatut & @yochannah 
I'd like you to review this PR, please.

I also have some questions about lines 88 & 91. Thank you!

**Comment by bebatut** [comment]
What are your questions?

**Comment by NPDebs** [comment]
> Thanks for the changes. They look good What are your questions?

Thank you! I enjoyed working on this.

I had doubts about whether it was necessary to make changes to the aforementioned lines of code...but your review has cleared that up.
Screenshot (256)

Finally, can I add a link to the documentation for Markdown language, in case anyone is new to it? (line 159)

**Comment by NPDebs** [comment]
> Yes for sure. Links are always good

Done!
Thank you so much for your guidance.

**Review by bebatut — APPROVED** [review]
The changes look good! Thanks a lot

**Comment by NPDebs** [comment]
You're most welcome. 😊🚀

**Pull request merged**
