### PR TITLE
Modify storage and template of cohort timeline and add next cohort files

### PR DESCRIPTION
**Pull request by bebatut**
- Move timeline to schedule file
- Remove cohort time include file
- Use a same timeline template for all cohort
- Modify the timeframe in weeks (only start date)
- Update the script to add content
- Add OLS-5 to OLS-8 file and timelines

### CODE REVIEW

**Comment by yochannah** [comment]
@bebatut Thanks for this! It looks like we might be missing a file - the deploy log says 

```
Liquid Exception: Could not find document '_ols-5/speaker-guide.md' in tag 'link'. Make sure the document exists and the path is correct. in ols-5.md
```

**Comment by bebatut** [comment]
I saw. The file is there so I do not understand the error. I realized after that I have the same locally but I could not figure out

**Review by yochannah — CHANGES_REQUESTED** [review]
@bebatut I think we're iterating through the wrong collection for the Schedule - the page is very short and the weeks aren't numbered:

sections missing content entirely under 'week weeks'

Other than that, happy to merge

**Comment by bebatut** [comment]
I will have a look tonight. Thanks for catching

**Comment by bebatut** [comment]
It should be fixed now

**Comment by yochannah** [comment]
🙌  Much better - I think we are still missing some dates though (or trying to output them when we don'tt need to?)

shows some weeks with 'date' or 'dates' but no text after the date prompt

**Comment by bebatut** [comment]
I should really connect my brain there.... I will have a look during the day

**Comment by bebatut** [comment]
I fixed that now:
image

What did I miss now??

**Review by yochannah — APPROVED** [review]
BOOM IT ALL WORKS 🕺

**Comment by bebatut** [comment]
Thanks @yochannah for the review :heart:

**Pull request merged**
