### PR TITLE
Made links more readable

### PR DESCRIPTION
**Pull request by 1Joda**
Screenshot (43)
I hovered over one of the links (guidelines and templates) so you'd see how it looks when its active and when its not

### CODE REVIEW

**Comment by Munnachienyi** [comment]
hello, @1Joda did you change the CSS style, how did you make the link's contrast readable?

**Comment by 1Joda** [comment]
> hello, @1Joda did you change the CSS style, how did you make the link's contrast readable?
I did
I left the color they used, removed the underline and made it the tiniest bit transparent so that when you click on it, it becomes opaque

**Comment by 1Joda** [comment]
I initially made it opaque and transparent on hover but it was blending in with the titles in the pages ('June 20, 2022' and 'guidelines and templates' for instance look similar but i was hovering over 'guidelines and templates) so i changed it

**Comment by bebatut** [comment]
There is already an issue #417 and a PR to review here #430 
Could you check the open PR and make suggestion there, instead of having a similar PR? Thanks a lot

**Comment by AndreaSanchezTapia** [comment]
I will close this issue but issue #417 and PR #430 are still open.

**Pull request closed without merging**
