### PR TITLE
OLS website UI fix

### PR DESCRIPTION
**Pull request by Bisola15**
I noticed that the screen mobile from the sample hence I followed suit. I did a rework on the background where the announcement is given if that is okay. I designed two samples with different colours because I couldn’t choose.

Please click on files changed to view the work. Don't know why it has these errors.

### CODE REVIEW

**Review by NPDebs — COMMENTED** [review]
These look really good @Bisola15! 💯
The first one gets my vote, for sure. The `color` is more in line with the already-existing brand identity.

Also, the last 3 names are missing spaces...and Yo's written is in lowercase.

Great job. 🚀

**Comment by Bisola15** [comment]
> These look really good @Bisola15! 💯 The first one gets my vote, for sure. The `color` is more in line with the already-existing brand identity.
> 
> Also, the last 3 names are missing spaces...and Yo's written is in lowercase.
> 
> Great job. 🚀

Thank You!! babes. I only saw the spaces after I pulled the requests smh. And I didn’t even notice the name till now 🤦🏽‍♀️🤦🏽‍♀️. Thank you for noticing. Thanks for the compliments 🥲❤️❤️

**Comment by vasconsaurus** [comment]
@Bisola15, I also love the green ❤️ I agree with @NPDebs that it's on brand. But I do like the image occupying the whole width, how it is today. But, that is completely subjective (and a completely unsolicited opinion 😆 )

**Comment by Bisola15** [comment]
> @Bisola15, I also love the green ❤️ I agree with @NPDebs that it's on brand. But I do like the image occupying the whole width, how it is today. But, that is completely subjective (and a completely unsolicited opinion 😆 )

Hi @vasconsaurus  I was just going through old mails and saw this. Must have missed the notification somehow. Thank you very much for your kind words ❤️ 
I see what you’re saying about the image occupying the whole width. I was trying to adhere as much as possible to the existing design pattern. Might play with it later and see the difference

**Comment by bebatut** [comment]
The content of the PR is outside the scope of this repository. I close the PR.  Thanks for the work there

**Pull request closed without merging**
