### PR TITLE
Build infrastructure for Catalyst sub-site

### PR DESCRIPTION
**Pull request by NPDebs**
The PR addresses issue #787, requesting more visibility for The [Catalyst](https://catalystproject.cloud/) project, on the OLS website.

**Changes made so far:**
- Created a landing page for the Catalyst (i.e `catalyst/index.md`).
- Added a new program to "cohort_names" dictionary (in `prepare_website_data.py` script).
- Prepared infrastructure for the new cohort (Catalyst i.e `cat-1`), by adding the `metadata`, `schedule` and `projects` yaml data files.
- Created a new script (`catalyst/update_schedule.sh`) to update schedule from planning sheet.
- Ran new script to update `x.yaml` files.

**To be done:**

- [ ] Add speakers and experts.
- [ ] Add people.
- [ ] Add projects.
- [x] Write logic to populate each `/cat-* page`.
- [x] Remind Taj to make planning sheet open.
- [ ] Give Catalyst a different feel by changing header images, etc.
- [ ] Link to new pages from the navbar.

**[Deploy preview](https://deploy-preview-788--ols-bebatut.netlify.app/catalyst/)** here...

**Note for reviewer(s):**
This PR is a work in progress, hence the "draft" status.

Thanks for the review!

### CODE REVIEW

**Comment by NPDebs** [comment]
💭 To avoid ultimately duplicating the already-existing Catalyst website, we should consider making some changes here.


**- Remove:**
    - the main catalyst ([index.md](https://4000-npdebs-openlifescienceg-ba0hj4s4ceh.ws-eu114.gitpod.io/catalyst/)) page.
    - remove the [index](https://4000-npdebs-openlifescienceg-ba0hj4s4ceh.ws-eu114.gitpod.io/catalyst/cat-1/) pages of each cohort.

**- Keep:**
- [Schedule](https://4000-npdebs-openlifescienceg-ba0hj4s4ceh.ws-eu114.gitpod.io/catalyst/cat-1/schedule)pages.
- [Project-participants](https://4000-npdebs-openlifescienceg-ba0hj4s4ceh.ws-eu114.gitpod.io/catalyst/cat-1/projects-participants) page


// @bebatut & @Tajuddeen1 - Please let me know if this makes sense and share your thoughts as well. 🙏

**Comment by NPDebs** [comment]
@Tajuddeen1 Do let know if you're comfortable with the info in the schedule page. 🙏

**Review by yochannah — APPROVED** [review]
looks good! Taj and I reviewed it and have a few comments - Taj will make issues for them now. 

One comment from my side: it's hard to find the catalyst page right now! I thought it might be under "catalyst" or under "open seeds".

**Review by Tajuddeen1 — APPROVED** [review]

**Comment by NPDebs** [comment]
> One comment from my side: it's hard to find the catalyst page right now! I thought it might be under "catalyst" or under "open seeds".

I had planned to link to the newly created pages from the navbar, as evidenced by the checklist item I haven't crossed off. 😅
I'll do that in a fresh PR. 🙏

**Comment by yochannah** [comment]
heh, sorry - Taj needed to be able to link to the pages so I got hasty with the merge button

**Comment by NPDebs** [comment]
Totally understandable! New PR ready at #793. 👍

**Pull request merged**
