### PR TITLE
Add Esther's mentoring blog

### PR DESCRIPTION
**Pull request by emmyft**
Thank you @estherplomp for writing this :100: Would you mind reviewing to check if it's OK? Thanks!

### CODE REVIEW

**Comment by EstherPlomp** [comment]
Can't seem to place a review or edit, so some minor changes, sorry: 

- " programme’s training component teaches" to "programme teaches" (line 29)
- "questions on or need" to "questions or needs" (line 29)
-  "my mentee and me" delete (line 29)
-  "starting with How" to "starting with how" (line 31)
-  "the meeting" to "meetings" (line 39, end)
- "will open" to "is open" (line 42) 

Sorry, I should have clearly read through this again before! Thanks for adding the blogpost!

**Comment by emmyft** [comment]
@EstherPlomp no problem! Check now?

**Comment by EstherPlomp** [comment]
Thanks for adjusting! The "need" on line 29 still needs an 's' behind it I think: 
- questions on or need" to "questions or needs" (line 29)

I think we're there otherwise, thank you!

**Comment by emmyft** [comment]
ahh sorry i missed that - but should be fixed now!

**Pull request merged**
