### PR TITLE
Logo branch - Design a logo for Open Life Science

### PR DESCRIPTION
**Pull request by htmluke**
New first ideas for the project. You can ask me anything: changes, new ideas, etc. I hope you like it <3

### CODE REVIEW

**Comment by yochannah** [comment]
@htmluke these look awesome! I like the yummy greens, and they way you've combined the helix with a leaf as well. One small note - the helix rotated in style2 looks a little like a figure 8 to me. I wonder if extending the helix a tiny bit on each end might help (or maybe not? lol).

**Comment by htmluke** [comment]
As sooner as possible I'll do that changes, and then we'll see if it looks better or not hahaha.

**Comment by bebatut** [comment]
Thanks @htmluke. It looks nice. I like the horizontal version

Just a few comments:
- Could you move the logo to `images/logo` folder?
- Could you export as PNG also?
- Which font did you use for the text? 
  
   It may be useful for us to know, to use the same in other communication media (e.g. flyer)

- Could you try with only one green tone?
- Is it normal the larger space between "Open" and "Life Science"?

Thanks a lot 😄

**Comment by htmluke** [comment]
Hi, I moved the file for images/logo-OLS, made new versions with one green tone as you asked me and also I exported all the files (including the new ones). The space  between "Open" and "Life Science" was purposeful, but I changed.
ps.: I putted a txt file with the basic information about the font and the color palette.

**Comment by xavierrollet** [comment]
Hi, i designed a logo, i'm new to Git Community. I Don't know how to suggest my logo in this branch. Can you help me :-)

**Comment by yochannah** [comment]
Hey @xavierrollet! :wave: Try having a look through this handy guide: https://guides.github.com/activities/forking/ and let us know if anything doesn't make sense! :D

**Comment by xavierrollet** [comment]
Hi thanks for your fast reply, i understand know, i cloned the master branch and tried to commit and push it..

So i forked the project and added the logo. i made a pull request. You can see the logo at https://github.com/xavierrollet/open-life-science.github.io/tree/master/images/logo

**Comment by yochannah** [comment]
@htmluke Thanks so much for this PR - some really great work 💯 

We'd like to add your name to our site footer to credit you for the logo - how would you like it to display? Something like this, maybe?

Logo by  [Lucas Emanoell Medeiros e Silva](https://github.com/htmluke).

**Comment by htmluke** [comment]
@yochannah of course i'd like it to, thanks a lot <333

**Pull request merged**
