### PR TITLE
Remove green dot and hover effect from cards.

### PR DESCRIPTION
**Pull request by NPDebs**
This PR fixes issue #709, which was solved in part by PR #741.

Two anomalies were observed around the cards:
- A green dot and
- a hover effect, as seen in here.

green_hover1

**Changes made:**
I noticed that the default styling of links included a green bottom border.
Both issues were handled by applying the styling below:

```
.container .columns.three-pillars .column {
  a {
    border-bottom: none;
  }
  a:hover {
    background-color: #fff;
  }
}
```

**Screenshot:**

green_hover2

**Deploy preview [here](https://deploy-preview-753--ols-bebatut.netlify.app/)...**

Thanks for the review!

### CODE REVIEW

**Comment by yochannah** [comment]
happy dancing human in bunny suit

**Comment by bebatut** [comment]
Thanks
Can you just check if it passes the accessibility tests?

**Comment by yochannah** [comment]
(Sorry @bebatut !! )

**Comment by NPDebs** [comment]
> Can you just check if it passes the accessibility tests?

Yep yep! I _Waved_ the pages and got this: 
_"Congratulations! No errors were detected!"_ 

Thanks for mentioning! ❤️

**Pull request merged**
