### PR TITLE
Cleaning step 1: People

### PR DESCRIPTION
**Pull request by bebatut**
First PR for some cleaning: people

- Move OLS-1 people to `people.yaml` to have only 1 location with people information and then avoid duplications if some become mentors or experts in next rounds
- Reformat people cards: smaller, more information, and expandable description

  	Screenshot 2020-05-08 at 22 44 58
 	 Screenshot 2020-05-08 at 22 45 12

### CODE REVIEW

**Comment by malvikasharan** [comment]
Looks great to me. Thank you so much @bebatut <3

**Comment by yochannah** [comment]
@bebatut this is fantastic! One small notem one the ols-1 project participants page everyone has lost their names: http://localhost:4000/ols-1/projects-participants/ - everything else looked great, and the open/close functionality for people cards is nice

image

**Comment by bebatut** [comment]
It should be fixed now :)

**Comment by bebatut** [comment]
I managed to clean partner cards:

Screenshot 2020-05-18 at 22 32 44

**Comment by malvikasharan** [comment]
@bebatut I had a look at this and I can't find anything to comment on. It is fantastic! Please go ahead and merge.

**Comment by bebatut** [comment]
Thanks @malvikasharan

**Pull request merged**
