### PR TITLE
To re-align the content on the stories page #433

### PR DESCRIPTION
**Pull request by oluwatobiBolu**
The images and heading are now aligned.
looks cleaner
however, the paragraph could not due to varying word count for different stories please review, looking forward to your feedback

### CODE REVIEW

**Comment by oluwatobiBolu** [comment]
> The images and heading are now aligned. looks cleaner however, the paragraph could not due to varying word count for different stories please review, looking forward to your feedback

Also i wasn't able to access/edit the html file, wanted to nest the p tags in block level element, so as to align dont know if that's a good idea
could you guide on how to access the html file.. i've gone through any method i know

**Comment by bebatut** [comment]
Could you add screenshots there to show the changes and explain the limitations?

**Comment by oluwatobiBolu** [comment]
> Could you add screenshots there to show the changes and explain the limitations? Thanks a lot

Screenshot (151)

Screenshot (152)

The heading and the images are all aligned
the limitations i faced was not totally aligning the content because they are not block-leveled
reviewing it again, i think that would put unnecessary lot of white space in some cards due varying word count of the paragraphs. let me know what you think , appreciate the feedback

**Comment by oluwatobiBolu** [comment]
@bebatut please on your own time i'd like hear your feedback on this too

**Comment by iremide1022** [comment]
Well done @oluwatobiBolu you have done a good job with this 💪🏿and I was going to ask about the white spaces is there anything that could be replaced there

**Pull request merged**
