### PR TITLE
Implement new logo

### PR DESCRIPTION
**Pull request by jilaga**
Paging superhero @NPDebs, `make serve-gitpod` worked!!!

### CODE REVIEW

**Comment by jilaga** [comment]
Thank you for calling my attention back to it. 🤲🏽

**Review by NPDebs — COMMENTED** [review]
Jilaga Nneoma, please forgive your sister. 🥲 I don't know how I missed this.

The PR looks really solid! 💪🏼 I can see Gitpod is no longer after your life. 😂

**One thing:** This belongs in the theme repo, please. Once it's up, I'll do the necessary updates, test and merge.

**Comment by jilaga** [comment]
Nope Debs! I no longer fly blind 😫. 

Thanks boss, Berenice already pointed that out so I fixed it. 
Would go ahead and draft this pr then 🤝

**Comment by NPDebs** [comment]
> Nope Debs! I no longer fly blind 😫.

I'm happy for you. 😂

> Berenice already pointed that out...

Always hundred steps ahead. 🤍

> Would go ahead and draft this pr then 🤝

I'll try to reply sooner this time.

**Pull request closed without merging**
