### PR TITLE
sitemap added

### PR DESCRIPTION
**Pull request by richarddushime**
Hi @bebatut @NPDebs 
Requesting for review 
i added the sitemap plugin  generator based on the instructions provided [here ](https://github.com/jekyll/jekyll-sitemap)
Fixed this issue #606

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks @richarddushime for the contribution. It looks good :)

**Comment by richarddushime** [comment]
> Thanks @richarddushime for the contribution. It looks good :)

Welcome @bebatut 
Happy that my contributions PR is merged

**Comment by richarddushime** [comment]
> Thanks @richarddushime for the contribution. It looks good :)

Welcome @bebatut 
Happy that my contribution PR is merged

**Comment by richarddushime** [comment]
> Thanks @richarddushime for the contribution. It looks good :)

Welcome @bebatut 
Happy that my contribution PR is merged

**Pull request merged**
