### PR TITLE
First round of addition of registered experts and mentors

### LINKED ISSUE #249: Organize mentors and experts in cohort page by expertise areas
- Extract all expertise areas of mentors for a cohort from their profile in `people.yaml` file
- Sort these areas
- Display mentors and experts given these areas

It will help to
- Match project to mentors
- Find experts for talks but also for expert calls

### PR DESCRIPTION
**Pull request by bebatut**
This PR:

- Add possible mentors and experts
- Fix #249: Organize mentors and experts in cohort page by expertise areas (not perfect)
  
  Screenshot 2021-01-07 at 22 17 40

### CODE REVIEW

**Comment by yochannah** [comment]
ah, @bebatut - really sorry, this appears to be a super big conflict. What would you recommend?

**Comment by bebatut** [comment]
I will have a look tonight

**Comment by bebatut** [comment]
It should be fixed now

**Review by yochannah — APPROVED** [review]
This looks good! there is something strange going on with Renato's profile (unode) but I don't think that should block the merge. 
image

**Pull request merged**
