### PR TITLE
Favicon [New PR ]

### PR DESCRIPTION
**Pull request by richarddushime**
Hi @NPDebs 
would you check this PR ?
Though there is no much modifications i made just the size of the  icon adjusted, 

[old PRs for this same issue Can be closed ]

### CODE REVIEW

**Comment by NPDebs** [comment]
Thanks so much, @richarddushime!

I'll have a look. 🔍 

Curious to know why you opened a new PR, rather than update the former one. :-)

**Comment by richarddushime** [comment]
> Thanks so much, @richarddushime!
> 
> I'll have a look. 🔍
> 
> Curious to know why you opened a new PR, rather than update the former one. :-)

Thanks 
I tried to build the old branch   and started playing games with me 
i had to  create a new one and redo it since its not that much work

**Review by NPDebs — APPROVED** [review]
Thank you, @richarddushime! PR looks good! 🎉 

One slight change made here was the use of Liquid's [link tag](https://jekyllrb.com/docs/liquid/tags/#links).

**Comment by NPDebs** [comment]
@bebatut Please have a look when you can. 🔍 
Merging this would allow us close the duplicates - #629 and #631.

**Review by bebatut — APPROVED** [review]
Thanks @richarddushime and @NPDebs

**Pull request merged**
